// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqdhohkstlunqbnwxgan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxZGhvaGtzdGx1bnFibnd4Z2FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1Nzg1NzEsImV4cCI6MjA2NTE1NDU3MX0.Do7W2iyRAPBhlGVTQJuEhowg_qYt9DJc-g_CO1w80b0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);